### PR TITLE
Added constructor to Order class

### PR DESCRIPTION
**Pull request by janakdom**
Added Order constructor and capacity validation (Capacity should be non-zero and positive number).

### CODE REVIEW

**Comment by rodi0878** [comment]
Please create a new test for verification of this new behaviour

**Comment by janakdom** [comment]
Test added. Please check now.

**Comment by rodi0878** [comment]
testPositiveCapacity is insufficient, without assert and/or expectedException this test can't fail and thus is useless

**Comment by janakdom** [comment]
testPositiveCapacity fixed

**Pull request merged**
